name: Test Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Mount cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Configure Bazel for coverage
        run: |
          cat >> .bazelrc << EOF
          coverage --combined_report=lcov
          coverage --coverage_report_generator=@bazel_tools//tools/test:coverage_report_generator
          coverage --experimental_generate_llvm_lcov
          test --test_output=errors
          build --verbose_failures
          EOF

      - name: Build all targets
        run: bazel build //...

      - name: Run tests
        run: bazel test //tests/...

      # TODO(add coverage)
